### PR TITLE
Remove qt references

### PR DESCRIPTION
**Pull request by rex4539**
Removed some more qt references.

I compiled it locally and didn't notice anything bad.

Let me know if any of the changes break something not obvious.

### CODE REVIEW

**Comment by adityapk00** [comment]
I tried this out, and all the changes seem fine, except the change in `src/scripts/control`. This file changes the debian package name, which breaks the upgrade from a `.deb` file on Linux. 

If you can undo that one file, I can merge this change in.

Thanks so much!

**Comment by rex4539** [comment]
Reverted that commit.

**Comment by rex4539** [comment]
Do you need anything else for this?

**Comment by adityapk00** [comment]
Oh shoot. This slipped my mind.

I’ll merge and release it tomorrow.

**Pull request merged**
