### PR TITLE
Themeability

### PR DESCRIPTION
**Pull request by earthorbit**
Please review this proposed dark mode and theme switching for the ZecWallet.

Many thanks to @miodragpop, @Oleksandrblack, and Martin for their incredible team effort as part of the Safecoin project (@fair-exchange).

EFasmlWVUAACgWU

### CODE REVIEW

**Comment by leto** [comment]
This looks like really nice work :+1:

**Comment by miodragpop** [comment]
Please guys, consider https://github.com/ZcashFoundation/zecwallet/pull/187 instead of this PR because I see a lot of conflicts here. The same functionality as this, yet created on top of zecwallet latest master src.

**Comment by miodragpop** [comment]
All translation files picked up some of Safecoin branding ...

**Comment by earthorbit** [comment]
> Please guys, consider #187 instead of this PR because I see a lot of possible collisions here. The same functionality as this, yet created on top of zecwallet latest master src.

Thank you @miodragpop , I've gone through the two PRs line by line, and cleaned this up based on your work.   Removing langauge and ui files which snuck in, a couple other catches, and your improvement in mainwindow.cpp.

Have done my best to preserve the original contributors in this PR but I need to mention that @miodragpop  definitely added more than shown to a number of key components.   In particular, providing the theme switching functionality.

**Comment by miodragpop** [comment]
Great, I will close PR #187 then.
Best regards from the whole Safecoin Team, keep up the good work !

**Comment by adityapk00** [comment]
This is absolutely fantastic. Thanks so much for your work! I'll merge it in today.

**Comment by adityapk00** [comment]
I had to make some small changes to make it work, please see here: 
5cff40c63ef4bb37a17b419c5532a5e5042228f5

**Comment by miodragpop** [comment]
Yeah, nice to have restart reminder. I've been trying to get all widgets repainted on style sheet change, without success so far. Feel free to customize css files to suite your needs. Hint: you can even use background transparency or colors with alpha channel.

**Comment by earthorbit** [comment]
> This is absolutely fantastic. Thanks so much for your work! I'll merge it in today.

Thank you so much for creating ZecWallet and continuing to develop it :)

**Pull request merged**
